version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.10.0
    commands:
      - npm install
  pre_build:
    commands:
        npm run build
        npm run postbuild
  build:
    commands:
      - zip -r Reciter-PubNotifier.zip *

artifacts:
  files: Reciter-PubNotifier.zip
