version: 0.2
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - npm run postbuild
artifacts:
  base-directory: 'dist' # Start the zip from inside the dist folder
  files:
    - '**/*'           # Include all compiled JS files
    - '../appspec.yml' # Go up one level to include the appspec
