version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "Zipping files..."
      - cd dist && zip -r ../Reciter-PubNotifier.zip . && cd ..
      - 'echo "Updating Lambda: $FUNCTION_NAME"'
      - aws lambda update-function-code --function-name "$DEPLOY_FUNCTION_NAME" --zip-file fileb://Reciter-PubNotifier.zip
artifacts:
  files:
    - Reciter-PubNotifier.zip
